### ISSUE TITLE
Can we get HR, but not LnHR in plot.HR?

### ISSUE THREAD

**Issue by waybo-zz** [arturstat/smoothHR#2]
In many medical studies, HR might be more frequently used than log HR. 
Can we plot HR, but not LnHR in plot.HR function?

For Example:
Lancet Diabetes Endocrinol 2015 
http://dx.doi.org/10.1016/
S2213-8587(15)00040-6

**Comment by arturstat** [comment]
Currently only log HR is implemented. I will see what I can do as regards implementing HR.

**Comment by arturstat** [comment]
It has been implemented. Please install the github version. Use ylog=FALSE. When ylog=FALSE, by default a logarithm scale is used on the y-axis. To use the non-logarithmic scale specify ylog=FALSE together with log="".
