### ISSUE TITLE
Error when using plot.HR

### ISSUE THREAD

**Issue by heleny2** [arturstat/smoothHR#3]
Hi, when I tried to use the plot.HR function, I got a warning about it. Here is complete warning information.
![image](https://user-images.githubusercontent.com/79426514/204936270-2d5e3433-2c1c-48e8-9103-a7abf9015a4c.png)

I compared my dataset and the example dataset, the variable types are all the same and the smoothHR function run successfully. Here is the result of print smoothHR.
![image](https://user-images.githubusercontent.com/79426514/204937294-6f134f72-f138-4b95-a32e-30fd52233a6f.png)

I'm wondering whether it's caused by the not significant predictor? And the hazard ratio curve conducted by other method shows that The min log HR is on the right end of the x axis. Maybe that's the possible reason?
![image](https://user-images.githubusercontent.com/79426514/204938764-caf3814d-e02f-4dd5-b236-9be4aa6dff72.png)

I didn't find any other have the same issue on the internet. Any advice will be appreciated. Thank you very much!

**Comment by arturstat** [comment]
Hi.
Did you try a different prob value?

**Comment by heleny2** [comment]
Yes, I tried different prob values and got similar warnings. Each of them said location XX don't exist and there is only 1 column.

**Comment by arturstat** [comment]
Looking at the warning message, it looks like "order" is returning indexes which do not exist in object "x". If you could send over the data, I could investigate more.

**Comment by heleny2** [comment]
Thank you so much for the response! I just cleaned the global environment and ran the code again and everything goes well now. Must conflict with something in the environment before. Thank you for building such a brilliant package!
