### ISSUE TITLE
option to return plot data

### ISSUE THREAD

**Issue by JulianMutz** [arturstat/smoothHR#4]
could we add an option to plot.HR() to return the data?

a starting point for this would be to add the below at the bottom of the plot.HR() function, just prior to the final closing curly brace

```
plot_data <- data.frame(x = a[jj, k],
                        y = tmat[jj, 1],
                        y.l95 = tmat[jj, 2],
                        y.u95 = tmat[jj, 3])
```

**Comment by arturstat** [comment]
@JulianMutz 
Your suggestion has just been implemented: https://github.com/arturstat/smoothHR/commit/664595fc0298a6f41081e2b22276a691734400a8
Please install via the [**remotes**](https://remotes.r-lib.org) package:
```r
remotes::install_github(
  repo="arturstat/smoothHR",
  build=TRUE,
  build_manual=TRUE
);
